language: node_js
node_js:
  - 0.12
install:
  - npm install
  - git config user.email "yaojingshuihudie@163.com"
  - git config user.name "Esther Li"
script:
  - hexo generate
  - hexo deploy