language: node_js
node_js: stable
install:
  - npm install
before_install:
  - git submodule update --init --remote --recursive
script:
  - hexo generate
after_script:
  - git config --global user.email "yaojingshuihudie@163.com"
  - git config --global user.name "29Esther"
  - hexo deploy