nav:
  Home: /
  Writing: /archives/
  ❤: /love/

customize:
    gravatar:
        email: test
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/29Esther
        weibo: http://weibo.com/2249721655/profile?topnav=1&wvr=6
        linkedin: https://www.linkedin.com/in/lizhixuan
    show_all_posts: true
    # post_count: 5
    highlight: tomorrow-night-bright

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: estherlzx
    google_analytics: UA-102069354-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
